#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: us
  identity:
    hostname: ubuntu-server
    username: ubuntu
    # Generate with: mkpasswd -m sha-512
    password: "$6$xyz$6CE.../..."  # Replace with your encrypted password
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - openssh-server
    - open-vm-tools
  storage:
    layout:
      name: direct
  network:
    network:
      version: 2
      ethernets:
        ens33:
          dhcp4: true
  user-data:
    disable_root: true
    package_update: true
    package_upgrade: true
  late-commands:
    - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu
    - chmod 440 /target/etc/sudoers.d/ubuntu